# Step 1: Use an official Node.js runtime as a base image
FROM node:16

# Step 2: Set the working directory inside the container
WORKDIR /usr/src/app

# Step 3: Copy package.json and package-lock.json
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the app’s code into the container
COPY . .

# prevent deployments from wiping the volume
# RUN mkdir -p /data/uploads && \
#     test -f /data/recipes.sqlite || cp /app/seed/recipes.sqlite /data/recipes.sqlite

# Step 6: Expose the port that the app will run on
EXPOSE 3000

# Step 7: Define the command to run the app
CMD ["npm", "start"]
